# **Analysis on Co2 Emissions**



**In this document, our objective is to delve into the dataset and conduct an analysis of the trends in carbon dioxide (CO2) emissions over the years. Given that CO2 significantly contributes to global warming, our exploration aims to identify and understand which continent exhibits the highest CO2 emissions throughout the years. Through this investigation, we aim to shed light on the environmental impact of CO2 emissions on a continental scale.**

# **Index**

1. Importing Libraries
2. Data Exploration
3. Data Featuring
4. Data Analysis
5. Conclusion

# 1. **Importing Libraries**

In [4]:
import numpy as np
import pandas as pd
import os

In [5]:
Main_data_set=pd.read_csv('/Users/harshjaiswal/Desktop/Git/CO2 Folder/production_based_co2_emissions.csv')

# 2. **Data Explorations**

In [6]:
Main_data_set

,ISO3,Country,Continent,Hemisphere,Metric tons of CO2e per capita (1990),Metric tons of CO2e per capita (1995),Metric tons of CO2e per capita (2000),Metric tons of CO2e per capita (2005),Metric tons of CO2e per capita (2010),Metric tons of CO2e per capita (2013),Metric tons of CO2e per capita (2018)
0,AFG,Afghanistan,Asia,Northern Hemisphere,1.24,0.84,0.82,0.76,1.06,1.40,2.66
1,ALB,Albania,Europe,Northern Hemisphere,3.56,2.15,2.36,2.68,2.83,2.85,3.52
2,DZA,Algeria,Africa,Northern Hemisphere,3.50,3.42,3.75,4.04,4.58,4.88,5.18
3,AGO,Angola,Africa,Southern Hemisphere,4.29,4.43,4.20,5.06,6.32,5.99,2.59
4,ATG,Antigua and Barbuda,America,Northern Hemisphere,6.31,6.53,7.08,8.77,10.69,11.22,12.59
...,...,...,...,...,...,...,...,...,...,...,...
176,VEN,Venezuela,America,Northern Hemisphere,8.62,8.73,8.70,8.85,9.08,8.85,8.10
177,VNM,Vietnam,Asia,Northern Hemisphere,1.03,1.25,1.63,2.16,2.80,2.81,3.94
178,YEM,Yemen,Asia,Northern Hemisphere,0.99,1.00,1.15,1.33,1.41,1.39,0.76
179,ZMB,Zambia,Africa,Southern Hemisphere,5.18,4.20,3.36,3.58,3.31,3.31,2.34
180,ZWE,Zimbabwe,Africa,Southern Hemisphere,3.25,2.62,2.47,1.93,1.81,1.82,2.17

In [7]:
Main_data_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181 entries, 0 to 180
Data columns (total 11 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   ISO3                                   181 non-null    object
 1   Country                                181 non-null    object
 2   Continent                              181 non-null    object
 3   Hemisphere                             181 non-null    object
 4   Metric tons of CO2e per capita (1990)  154 non-null    float64
 5   Metric tons of CO2e per capita (1995)  177 non-null    float64
 6   Metric tons of CO2e per capita (2000)  179 non-null    float64
 7   Metric tons of CO2e per capita (2005)  179 non-null    float64
 8   Metric tons of CO2e per capita (2010)  181 non-null    float64
 9   Metric tons of CO2e per capita (2013)  180 non-null    float64
 10  Metric tons of CO2e per capita (2018)  180 non-null    float64
dtypes: float64(7), object(4)
memory usage: 15.7+ KB

In [8]:
Main_data_set.isna().sum()

ISO3                                      0
Country                                   0
Continent                                 0
Hemisphere                                0
Metric tons of CO2e per capita (1990)    27
Metric tons of CO2e per capita (1995)     4
Metric tons of CO2e per capita (2000)     2
Metric tons of CO2e per capita (2005)     2
Metric tons of CO2e per capita (2010)     0
Metric tons of CO2e per capita (2013)     1
Metric tons of CO2e per capita (2018)     1
dtype: int64

# 3. **Data Featuring**

In [9]:
Main_data_set[Main_data_set['Metric tons of CO2e per capita (1990)'].isna()]

,ISO3,Country,Continent,Hemisphere,Metric tons of CO2e per capita (1990),Metric tons of CO2e per capita (1995),Metric tons of CO2e per capita (2000),Metric tons of CO2e per capita (2005),Metric tons of CO2e per capita (2010),Metric tons of CO2e per capita (2013),Metric tons of CO2e per capita (2018)
6,ARM,Armenia,Asia,Northern Hemisphere,NaN,1.94,1.82,2.30,2.46,2.97,3.17
9,AZE,Azerbaijan,Asia,Northern Hemisphere,NaN,7.50,6.79,6.61,6.36,7.43,8.07
14,BLR,Belarus,Europe,Northern Hemisphere,NaN,8.23,7.84,8.63,9.66,9.55,9.29
15,BEL,Belgium,Europe,Northern Hemisphere,NaN,NaN,13.26,12.16,11.44,10.17,9.52
20,BIH,Bosnia and Herzegovina,Europe,Northern Hemisphere,NaN,1.81,5.34,6.00,7.36,7.89,8.18
38,HRV,Croatia,Europe,Northern Hemisphere,NaN,4.64,5.41,6.40,5.99,5.49,5.52
41,CZE,Czech Republic,Europe,Northern Hemisphere,NaN,14.05,13.76,13.47,12.39,11.42,11.56
50,ERI,Eritrea,Africa,Northern Hemisphere,NaN,1.96,1.95,1.63,1.44,1.44,NaN
51,EST,Estonia,Europe,Northern Hemisphere,NaN,14.40,13.53,15.77,17.30,17.66,14.07
53,ETH,Ethiopia,Africa,Northern Hemisphere,NaN,1.11,1.09,1.16,1.31,1.30,1.58
59,GEO,Georgia,Asia,Northern Hemisphere,NaN,2.88,2.78,2.61,2.91,3.66,4.54
83,KAZ,Kazakhstan,Asia,Northern Hemisphere,NaN,14.43,10.37,13.73,17.28,18.23,15.00
87,KGZ,Kyrgyzstan,Asia,Northern Hemisphere,NaN,2.06,1.85,1.97,2.16,2.73,2.87
89,LVA,Latvia,Europe,Northern Hemisphere,NaN,5.43,4.66,5.47,6.29,6.20,6.05
94,LTU,Lithuania,Europe,Northern Hemisphere,NaN,6.07,5.55,6.51,6.65,6.45,6.73
95,LUX,Luxembourg,Europe,Northern Hemisphere,NaN,NaN,21.14,27.86,23.82,20.72,16.81
105,MDA,Moldova,Europe,Northern Hemisphere,NaN,4.12,2.60,2.91,3.02,2.82,4.87
107,MNE,Montenegro,Europe,Northern Hemisphere,NaN,NaN,NaN,NaN,5.81,5.40,6.11
123,PLW,Palau,Oceania,Northern Hemisphere,NaN,6.98,6.74,10.30,11.64,17.03,17.93
134,RUS,Russia,Europe,Northern Hemisphere,NaN,14.45,13.92,14.70,15.21,15.31,17.60
143,SRB,Serbia,Europe,Northern Hemisphere,NaN,NaN,NaN,NaN,6.54,6.62,8.96
147,SVK,Slovakia,Europe,Northern Hemisphere,NaN,9.36,8.48,8.68,7.90,7.43,7.33
148,SVN,Slovenia,Europe,Northern Hemisphere,NaN,8.92,9.01,9.67,9.30,8.72,8.28
159,TJK,Tajikistan,Asia,Northern Hemisphere,NaN,1.28,0.98,1.04,1.10,1.25,1.67
167,TKM,Turkmenistan,Asia,Northern Hemisphere,NaN,13.39,14.51,18.13,19.44,20.93,21.38
169,UKR,Ukraine,Europe,Northern Hemisphere,NaN,10.41,8.25,8.54,8.13,8.33,6.15
174,UZB,Uzbekistan,Asia,Northern Hemisphere,NaN,7.90,8.40,7.85,7.55,7.52,7.15

In [10]:
Main_data_set[1:10]

,ISO3,Country,Continent,Hemisphere,Metric tons of CO2e per capita (1990),Metric tons of CO2e per capita (1995),Metric tons of CO2e per capita (2000),Metric tons of CO2e per capita (2005),Metric tons of CO2e per capita (2010),Metric tons of CO2e per capita (2013),Metric tons of CO2e per capita (2018)
1,ALB,Albania,Europe,Northern Hemisphere,3.56,2.15,2.36,2.68,2.83,2.85,3.52
2,DZA,Algeria,Africa,Northern Hemisphere,3.50,3.42,3.75,4.04,4.58,4.88,5.18
3,AGO,Angola,Africa,Southern Hemisphere,4.29,4.43,4.20,5.06,6.32,5.99,2.59
4,ATG,Antigua and Barbuda,America,Northern Hemisphere,6.31,6.53,7.08,8.77,10.69,11.22,12.59
5,ARG,Argentina,America,Southern Hemisphere,7.12,7.25,7.49,7.73,7.77,7.86,8.22
6,ARM,Armenia,Asia,Northern Hemisphere,NaN,1.94,1.82,2.30,2.46,2.97,3.17
7,AUS,Australia,Oceania,Southern Hemisphere,28.06,27.28,30.84,27.60,25.39,25.06,24.63
8,AUT,Austria,Europe,Northern Hemisphere,9.71,9.55,9.59,10.79,9.85,9.15,8.48
9,AZE,Azerbaijan,Asia,Northern Hemisphere,NaN,7.50,6.79,6.61,6.36,7.43,8.07

In [11]:
Main_data_set[Main_data_set['Country']=='Armenia']

,ISO3,Country,Continent,Hemisphere,Metric tons of CO2e per capita (1990),Metric tons of CO2e per capita (1995),Metric tons of CO2e per capita (2000),Metric tons of CO2e per capita (2005),Metric tons of CO2e per capita (2010),Metric tons of CO2e per capita (2013),Metric tons of CO2e per capita (2018)
6,ARM,Armenia,Asia,Northern Hemisphere,NaN,1.94,1.82,2.3,2.46,2.97,3.17

In [12]:
Main_data_set['Country'].value_counts()

Afghanistan    1
Netherlands    1
Nicaragua      1
Niger          1
Nigeria        1
              ..
Greece         1
Grenada        1
Guatemala      1
Guinea         1
Zimbabwe       1
Name: Country, Length: 181, dtype: int64

In [13]:
Main_data_set['Continent'].value_counts()

Africa     51
Asia       46
Europe     38
America    35
Oceania    11
Name: Continent, dtype: int64

In [14]:
Copy_data_set=Main_data_set.copy()

In [15]:
Copy_data_set

,ISO3,Country,Continent,Hemisphere,Metric tons of CO2e per capita (1990),Metric tons of CO2e per capita (1995),Metric tons of CO2e per capita (2000),Metric tons of CO2e per capita (2005),Metric tons of CO2e per capita (2010),Metric tons of CO2e per capita (2013),Metric tons of CO2e per capita (2018)
0,AFG,Afghanistan,Asia,Northern Hemisphere,1.24,0.84,0.82,0.76,1.06,1.40,2.66
1,ALB,Albania,Europe,Northern Hemisphere,3.56,2.15,2.36,2.68,2.83,2.85,3.52
2,DZA,Algeria,Africa,Northern Hemisphere,3.50,3.42,3.75,4.04,4.58,4.88,5.18
3,AGO,Angola,Africa,Southern Hemisphere,4.29,4.43,4.20,5.06,6.32,5.99,2.59
4,ATG,Antigua and Barbuda,America,Northern Hemisphere,6.31,6.53,7.08,8.77,10.69,11.22,12.59
...,...,...,...,...,...,...,...,...,...,...,...
176,VEN,Venezuela,America,Northern Hemisphere,8.62,8.73,8.70,8.85,9.08,8.85,8.10
177,VNM,Vietnam,Asia,Northern Hemisphere,1.03,1.25,1.63,2.16,2.80,2.81,3.94
178,YEM,Yemen,Asia,Northern Hemisphere,0.99,1.00,1.15,1.33,1.41,1.39,0.76
179,ZMB,Zambia,Africa,Southern Hemisphere,5.18,4.20,3.36,3.58,3.31,3.31,2.34
180,ZWE,Zimbabwe,Africa,Southern Hemisphere,3.25,2.62,2.47,1.93,1.81,1.82,2.17

In [16]:
Copy_data_set[Copy_data_set['Metric tons of CO2e per capita (1990)'].isna()]

,ISO3,Country,Continent,Hemisphere,Metric tons of CO2e per capita (1990),Metric tons of CO2e per capita (1995),Metric tons of CO2e per capita (2000),Metric tons of CO2e per capita (2005),Metric tons of CO2e per capita (2010),Metric tons of CO2e per capita (2013),Metric tons of CO2e per capita (2018)
6,ARM,Armenia,Asia,Northern Hemisphere,NaN,1.94,1.82,2.30,2.46,2.97,3.17
9,AZE,Azerbaijan,Asia,Northern Hemisphere,NaN,7.50,6.79,6.61,6.36,7.43,8.07
14,BLR,Belarus,Europe,Northern Hemisphere,NaN,8.23,7.84,8.63,9.66,9.55,9.29
15,BEL,Belgium,Europe,Northern Hemisphere,NaN,NaN,13.26,12.16,11.44,10.17,9.52
20,BIH,Bosnia and Herzegovina,Europe,Northern Hemisphere,NaN,1.81,5.34,6.00,7.36,7.89,8.18
38,HRV,Croatia,Europe,Northern Hemisphere,NaN,4.64,5.41,6.40,5.99,5.49,5.52
41,CZE,Czech Republic,Europe,Northern Hemisphere,NaN,14.05,13.76,13.47,12.39,11.42,11.56
50,ERI,Eritrea,Africa,Northern Hemisphere,NaN,1.96,1.95,1.63,1.44,1.44,NaN
51,EST,Estonia,Europe,Northern Hemisphere,NaN,14.40,13.53,15.77,17.30,17.66,14.07
53,ETH,Ethiopia,Africa,Northern Hemisphere,NaN,1.11,1.09,1.16,1.31,1.30,1.58
59,GEO,Georgia,Asia,Northern Hemisphere,NaN,2.88,2.78,2.61,2.91,3.66,4.54
83,KAZ,Kazakhstan,Asia,Northern Hemisphere,NaN,14.43,10.37,13.73,17.28,18.23,15.00
87,KGZ,Kyrgyzstan,Asia,Northern Hemisphere,NaN,2.06,1.85,1.97,2.16,2.73,2.87
89,LVA,Latvia,Europe,Northern Hemisphere,NaN,5.43,4.66,5.47,6.29,6.20,6.05
94,LTU,Lithuania,Europe,Northern Hemisphere,NaN,6.07,5.55,6.51,6.65,6.45,6.73
95,LUX,Luxembourg,Europe,Northern Hemisphere,NaN,NaN,21.14,27.86,23.82,20.72,16.81
105,MDA,Moldova,Europe,Northern Hemisphere,NaN,4.12,2.60,2.91,3.02,2.82,4.87
107,MNE,Montenegro,Europe,Northern Hemisphere,NaN,NaN,NaN,NaN,5.81,5.40,6.11
123,PLW,Palau,Oceania,Northern Hemisphere,NaN,6.98,6.74,10.30,11.64,17.03,17.93
134,RUS,Russia,Europe,Northern Hemisphere,NaN,14.45,13.92,14.70,15.21,15.31,17.60
143,SRB,Serbia,Europe,Northern Hemisphere,NaN,NaN,NaN,NaN,6.54,6.62,8.96
147,SVK,Slovakia,Europe,Northern Hemisphere,NaN,9.36,8.48,8.68,7.90,7.43,7.33
148,SVN,Slovenia,Europe,Northern Hemisphere,NaN,8.92,9.01,9.67,9.30,8.72,8.28
159,TJK,Tajikistan,Asia,Northern Hemisphere,NaN,1.28,0.98,1.04,1.10,1.25,1.67
167,TKM,Turkmenistan,Asia,Northern Hemisphere,NaN,13.39,14.51,18.13,19.44,20.93,21.38
169,UKR,Ukraine,Europe,Northern Hemisphere,NaN,10.41,8.25,8.54,8.13,8.33,6.15
174,UZB,Uzbekistan,Asia,Northern Hemisphere,NaN,7.90,8.40,7.85,7.55,7.52,7.15

In [17]:
values_1990=Copy_data_set[Copy_data_set['Metric tons of CO2e per capita (1990)'].isna()]

In [18]:
values_1990['Metric tons of CO2e per capita (1990)']=values_1990['Metric tons of CO2e per capita (1995)']
values_1990

/var/folders/g_/4y5h37m96h7gb1f4w331kclw0000gn/T/ipykernel_41646/3874575710.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  values_1990['Metric tons of CO2e per capita (1990)']=values_1990['Metric tons of CO2e per capita (1995)']

,ISO3,Country,Continent,Hemisphere,Metric tons of CO2e per capita (1990),Metric tons of CO2e per capita (1995),Metric tons of CO2e per capita (2000),Metric tons of CO2e per capita (2005),Metric tons of CO2e per capita (2010),Metric tons of CO2e per capita (2013),Metric tons of CO2e per capita (2018)
6,ARM,Armenia,Asia,Northern Hemisphere,1.94,1.94,1.82,2.30,2.46,2.97,3.17
9,AZE,Azerbaijan,Asia,Northern Hemisphere,7.50,7.50,6.79,6.61,6.36,7.43,8.07
14,BLR,Belarus,Europe,Northern Hemisphere,8.23,8.23,7.84,8.63,9.66,9.55,9.29
15,BEL,Belgium,Europe,Northern Hemisphere,NaN,NaN,13.26,12.16,11.44,10.17,9.52
20,BIH,Bosnia and Herzegovina,Europe,Northern Hemisphere,1.81,1.81,5.34,6.00,7.36,7.89,8.18
38,HRV,Croatia,Europe,Northern Hemisphere,4.64,4.64,5.41,6.40,5.99,5.49,5.52
41,CZE,Czech Republic,Europe,Northern Hemisphere,14.05,14.05,13.76,13.47,12.39,11.42,11.56
50,ERI,Eritrea,Africa,Northern Hemisphere,1.96,1.96,1.95,1.63,1.44,1.44,NaN
51,EST,Estonia,Europe,Northern Hemisphere,14.40,14.40,13.53,15.77,17.30,17.66,14.07
53,ETH,Ethiopia,Africa,Northern Hemisphere,1.11,1.11,1.09,1.16,1.31,1.30,1.58
59,GEO,Georgia,Asia,Northern Hemisphere,2.88,2.88,2.78,2.61,2.91,3.66,4.54
83,KAZ,Kazakhstan,Asia,Northern Hemisphere,14.43,14.43,10.37,13.73,17.28,18.23,15.00
87,KGZ,Kyrgyzstan,Asia,Northern Hemisphere,2.06,2.06,1.85,1.97,2.16,2.73,2.87
89,LVA,Latvia,Europe,Northern Hemisphere,5.43,5.43,4.66,5.47,6.29,6.20,6.05
94,LTU,Lithuania,Europe,Northern Hemisphere,6.07,6.07,5.55,6.51,6.65,6.45,6.73
95,LUX,Luxembourg,Europe,Northern Hemisphere,NaN,NaN,21.14,27.86,23.82,20.72,16.81
105,MDA,Moldova,Europe,Northern Hemisphere,4.12,4.12,2.60,2.91,3.02,2.82,4.87
107,MNE,Montenegro,Europe,Northern Hemisphere,NaN,NaN,NaN,NaN,5.81,5.40,6.11
123,PLW,Palau,Oceania,Northern Hemisphere,6.98,6.98,6.74,10.30,11.64,17.03,17.93
134,RUS,Russia,Europe,Northern Hemisphere,14.45,14.45,13.92,14.70,15.21,15.31,17.60
143,SRB,Serbia,Europe,Northern Hemisphere,NaN,NaN,NaN,NaN,6.54,6.62,8.96
147,SVK,Slovakia,Europe,Northern Hemisphere,9.36,9.36,8.48,8.68,7.90,7.43,7.33
148,SVN,Slovenia,Europe,Northern Hemisphere,8.92,8.92,9.01,9.67,9.30,8.72,8.28
159,TJK,Tajikistan,Asia,Northern Hemisphere,1.28,1.28,0.98,1.04,1.10,1.25,1.67
167,TKM,Turkmenistan,Asia,Northern Hemisphere,13.39,13.39,14.51,18.13,19.44,20.93,21.38
169,UKR,Ukraine,Europe,Northern Hemisphere,10.41,10.41,8.25,8.54,8.13,8.33,6.15
174,UZB,Uzbekistan,Asia,Northern Hemisphere,7.90,7.90,8.40,7.85,7.55,7.52,7.15

In [19]:
Copy_data_set['Metric tons of CO2e per capita (1990)'].fillna(values_1990['Metric tons of CO2e per capita (1990)'],inplace=True)

In [20]:
Copy_data_set[Copy_data_set['Metric tons of CO2e per capita (1990)'].isna()]

,ISO3,Country,Continent,Hemisphere,Metric tons of CO2e per capita (1990),Metric tons of CO2e per capita (1995),Metric tons of CO2e per capita (2000),Metric tons of CO2e per capita (2005),Metric tons of CO2e per capita (2010),Metric tons of CO2e per capita (2013),Metric tons of CO2e per capita (2018)
15,BEL,Belgium,Europe,Northern Hemisphere,NaN,NaN,13.26,12.16,11.44,10.17,9.52
95,LUX,Luxembourg,Europe,Northern Hemisphere,NaN,NaN,21.14,27.86,23.82,20.72,16.81
107,MNE,Montenegro,Europe,Northern Hemisphere,NaN,NaN,NaN,NaN,5.81,5.40,6.11
143,SRB,Serbia,Europe,Northern Hemisphere,NaN,NaN,NaN,NaN,6.54,6.62,8.96

In [21]:
Remaing_values=Copy_data_set[Copy_data_set['Metric tons of CO2e per capita (1990)'].isna()]

In [22]:
Remaining_values=Remaing_values['Metric tons of CO2e per capita (2000)']

In [23]:
Remaing_values

,ISO3,Country,Continent,Hemisphere,Metric tons of CO2e per capita (1990),Metric tons of CO2e per capita (1995),Metric tons of CO2e per capita (2000),Metric tons of CO2e per capita (2005),Metric tons of CO2e per capita (2010),Metric tons of CO2e per capita (2013),Metric tons of CO2e per capita (2018)
15,BEL,Belgium,Europe,Northern Hemisphere,NaN,NaN,13.26,12.16,11.44,10.17,9.52
95,LUX,Luxembourg,Europe,Northern Hemisphere,NaN,NaN,21.14,27.86,23.82,20.72,16.81
107,MNE,Montenegro,Europe,Northern Hemisphere,NaN,NaN,NaN,NaN,5.81,5.40,6.11
143,SRB,Serbia,Europe,Northern Hemisphere,NaN,NaN,NaN,NaN,6.54,6.62,8.96

In [24]:
Copy_data_set['Metric tons of CO2e per capita (1990)'].fillna(Remaing_values['Metric tons of CO2e per capita (2000)'],inplace=True)

In [25]:
Copy_data_set[Copy_data_set['Metric tons of CO2e per capita (1990)'].isna()]

,ISO3,Country,Continent,Hemisphere,Metric tons of CO2e per capita (1990),Metric tons of CO2e per capita (1995),Metric tons of CO2e per capita (2000),Metric tons of CO2e per capita (2005),Metric tons of CO2e per capita (2010),Metric tons of CO2e per capita (2013),Metric tons of CO2e per capita (2018)
107,MNE,Montenegro,Europe,Northern Hemisphere,NaN,NaN,NaN,NaN,5.81,5.40,6.11
143,SRB,Serbia,Europe,Northern Hemisphere,NaN,NaN,NaN,NaN,6.54,6.62,8.96

In [26]:
Copy_data_set['Metric tons of CO2e per capita (1990)'].fillna(Remaing_values['Metric tons of CO2e per capita (2010)'],inplace=True)

In [27]:
Copy_data_set[Copy_data_set['Metric tons of CO2e per capita (1990)'].isna()]

Empty DataFrame
Columns: [ISO3, Country, Continent, Hemisphere, Metric tons of CO2e per capita (1990), Metric tons of CO2e per capita (1995), Metric tons of CO2e per capita (2000), Metric tons of CO2e per capita (2005), Metric tons of CO2e per capita (2010), Metric tons of CO2e per capita (2013), Metric tons of CO2e per capita (2018)]
Index: []

In [28]:
Copy_data_set['Metric tons of CO2e per capita (1995)'].fillna(Copy_data_set['Metric tons of CO2e per capita (1990)'],inplace=True)

In [29]:
Copy_data_set['Metric tons of CO2e per capita (1995)'].isna().value_counts()

False    181
Name: Metric tons of CO2e per capita (1995), dtype: int64

In [30]:
Copy_data_set[Copy_data_set['Metric tons of CO2e per capita (2000)'].isna()]

,ISO3,Country,Continent,Hemisphere,Metric tons of CO2e per capita (1990),Metric tons of CO2e per capita (1995),Metric tons of CO2e per capita (2000),Metric tons of CO2e per capita (2005),Metric tons of CO2e per capita (2010),Metric tons of CO2e per capita (2013),Metric tons of CO2e per capita (2018)
107,MNE,Montenegro,Europe,Northern Hemisphere,5.81,5.81,NaN,NaN,5.81,5.40,6.11
143,SRB,Serbia,Europe,Northern Hemisphere,6.54,6.54,NaN,NaN,6.54,6.62,8.96

In [31]:
Copy_data_set['Metric tons of CO2e per capita (2000)'].fillna(Copy_data_set['Metric tons of CO2e per capita (2010)'],inplace=True)

In [32]:
Copy_data_set['Metric tons of CO2e per capita (2000)'].isna().value_counts()

False    181
Name: Metric tons of CO2e per capita (2000), dtype: int64

In [33]:
Copy_data_set[Copy_data_set['Metric tons of CO2e per capita (2005)'].isna()]

,ISO3,Country,Continent,Hemisphere,Metric tons of CO2e per capita (1990),Metric tons of CO2e per capita (1995),Metric tons of CO2e per capita (2000),Metric tons of CO2e per capita (2005),Metric tons of CO2e per capita (2010),Metric tons of CO2e per capita (2013),Metric tons of CO2e per capita (2018)
107,MNE,Montenegro,Europe,Northern Hemisphere,5.81,5.81,5.81,NaN,5.81,5.40,6.11
143,SRB,Serbia,Europe,Northern Hemisphere,6.54,6.54,6.54,NaN,6.54,6.62,8.96

In [34]:
Copy_data_set['Metric tons of CO2e per capita (2005)'].fillna(Copy_data_set['Metric tons of CO2e per capita (2010)'],inplace=True)

In [35]:
Copy_data_set.isna().value_counts()

ISO3   Country  Continent  Hemisphere  Metric tons of CO2e per capita (1990)  Metric tons of CO2e per capita (1995)  Metric tons of CO2e per capita (2000)  Metric tons of CO2e per capita (2005)  Metric tons of CO2e per capita (2010)  Metric tons of CO2e per capita (2013)  Metric tons of CO2e per capita (2018)
False  False    False      False       False                                  False                                  False                                  False                                  False                                  False                                  False                                    179
                                                                                                                                                                                                                                                                                 True                                       1
                                                                                                                                                                                                                                          True                                   False                                      1
dtype: int64

In [36]:
Copy_data_set[Copy_data_set['Metric tons of CO2e per capita (2013)'].isna()]

,ISO3,Country,Continent,Hemisphere,Metric tons of CO2e per capita (1990),Metric tons of CO2e per capita (1995),Metric tons of CO2e per capita (2000),Metric tons of CO2e per capita (2005),Metric tons of CO2e per capita (2010),Metric tons of CO2e per capita (2013),Metric tons of CO2e per capita (2018)
154,SDN,Sudan,Africa,Northern Hemisphere,3.83,3.9,4.38,4.57,4.27,NaN,2.62

In [37]:
Metric_tons=Copy_data_set[Copy_data_set['Country']=='Sudan']
Metric_tons_2010=Metric_tons['Metric tons of CO2e per capita (2010)']
Metric_tons_2018= Metric_tons['Metric tons of CO2e per capita (2018)']
Avg_sudan=(Metric_tons_2010+Metric_tons_2018)/2
Copy_data_set['Metric tons of CO2e per capita (2013)'].fillna(Avg_sudan,inplace=True)

In [38]:
Copy_data_set.isna().value_counts()

ISO3   Country  Continent  Hemisphere  Metric tons of CO2e per capita (1990)  Metric tons of CO2e per capita (1995)  Metric tons of CO2e per capita (2000)  Metric tons of CO2e per capita (2005)  Metric tons of CO2e per capita (2010)  Metric tons of CO2e per capita (2013)  Metric tons of CO2e per capita (2018)
False  False    False      False       False                                  False                                  False                                  False                                  False                                  False                                  False                                    180
                                                                                                                                                                                                                                                                                 True                                       1
dtype: int64

In [39]:
Copy_data_set[Copy_data_set['Metric tons of CO2e per capita (2018)'].isna()]

,ISO3,Country,Continent,Hemisphere,Metric tons of CO2e per capita (1990),Metric tons of CO2e per capita (1995),Metric tons of CO2e per capita (2000),Metric tons of CO2e per capita (2005),Metric tons of CO2e per capita (2010),Metric tons of CO2e per capita (2013),Metric tons of CO2e per capita (2018)
50,ERI,Eritrea,Africa,Northern Hemisphere,1.96,1.96,1.95,1.63,1.44,1.44,NaN

In [40]:
Copy_data_set['Metric tons of CO2e per capita (2018)'].fillna(Copy_data_set['Metric tons of CO2e per capita (2013)'],inplace=True)

In [41]:
Copy_data_set[Copy_data_set['Metric tons of CO2e per capita (2018)'].isna()]

Empty DataFrame
Columns: [ISO3, Country, Continent, Hemisphere, Metric tons of CO2e per capita (1990), Metric tons of CO2e per capita (1995), Metric tons of CO2e per capita (2000), Metric tons of CO2e per capita (2005), Metric tons of CO2e per capita (2010), Metric tons of CO2e per capita (2013), Metric tons of CO2e per capita (2018)]
Index: []

In [42]:
Copy_data_set.isna().value_counts()

ISO3   Country  Continent  Hemisphere  Metric tons of CO2e per capita (1990)  Metric tons of CO2e per capita (1995)  Metric tons of CO2e per capita (2000)  Metric tons of CO2e per capita (2005)  Metric tons of CO2e per capita (2010)  Metric tons of CO2e per capita (2013)  Metric tons of CO2e per capita (2018)
False  False    False      False       False                                  False                                  False                                  False                                  False                                  False                                  False                                    181
dtype: int64

In [43]:
Copy_data_set.describe()

,Metric tons of CO2e per capita (1990),Metric tons of CO2e per capita (1995),Metric tons of CO2e per capita (2000),Metric tons of CO2e per capita (2005),Metric tons of CO2e per capita (2010),Metric tons of CO2e per capita (2013),Metric tons of CO2e per capita (2018)
count,181.000000,181.000000,181.000000,181.000000,181.000000,181.000000,181.000000
mean,6.738785,6.974530,7.040166,7.394972,7.226464,7.116436,6.765249
std,7.589620,8.794219,8.590142,9.289593,8.239457,7.883082,6.550726
min,0.420000,0.420000,0.350000,0.260000,0.290000,0.320000,0.490000
25%,1.740000,1.690000,1.760000,1.930000,1.960000,1.920000,2.340000
50%,3.830000,4.130000,4.400000,4.660000,4.730000,4.870000,4.870000
75%,8.920000,8.730000,8.830000,9.480000,9.300000,9.040000,8.480000
max,48.330000,73.130000,65.640000,76.410000,62.470000,54.410000,38.750000

In [44]:
Copy_data_set

,ISO3,Country,Continent,Hemisphere,Metric tons of CO2e per capita (1990),Metric tons of CO2e per capita (1995),Metric tons of CO2e per capita (2000),Metric tons of CO2e per capita (2005),Metric tons of CO2e per capita (2010),Metric tons of CO2e per capita (2013),Metric tons of CO2e per capita (2018)
0,AFG,Afghanistan,Asia,Northern Hemisphere,1.24,0.84,0.82,0.76,1.06,1.40,2.66
1,ALB,Albania,Europe,Northern Hemisphere,3.56,2.15,2.36,2.68,2.83,2.85,3.52
2,DZA,Algeria,Africa,Northern Hemisphere,3.50,3.42,3.75,4.04,4.58,4.88,5.18
3,AGO,Angola,Africa,Southern Hemisphere,4.29,4.43,4.20,5.06,6.32,5.99,2.59
4,ATG,Antigua and Barbuda,America,Northern Hemisphere,6.31,6.53,7.08,8.77,10.69,11.22,12.59
...,...,...,...,...,...,...,...,...,...,...,...
176,VEN,Venezuela,America,Northern Hemisphere,8.62,8.73,8.70,8.85,9.08,8.85,8.10
177,VNM,Vietnam,Asia,Northern Hemisphere,1.03,1.25,1.63,2.16,2.80,2.81,3.94
178,YEM,Yemen,Asia,Northern Hemisphere,0.99,1.00,1.15,1.33,1.41,1.39,0.76
179,ZMB,Zambia,Africa,Southern Hemisphere,5.18,4.20,3.36,3.58,3.31,3.31,2.34
180,ZWE,Zimbabwe,Africa,Southern Hemisphere,3.25,2.62,2.47,1.93,1.81,1.82,2.17

# 4.  **Data Visualization**

In [45]:
from matplotlib import pyplot as plt
import seaborn as sns;
import plotly.express as px
import panel as pn
import pandas_bokeh;
pn.extension('tabulator')
import plotly.graph_objects as go

import hvplot.pandas

ModuleNotFoundError: No module named 'pandas_bokeh'

In [ ]:
numeric_data=Copy_data_set.select_dtypes(include=[np.number])
Correlation_matrix=numeric_data.corr()
plt.figure(figsize=(12, 8))
sns.heatmap(Correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.title('Correlation Matrix')
plt.show()

The correlations are slightly weaker between non-adjacent years, but they are still very strong. For example, the correlation between 1990 and 2000 is 0.91, and the correlation between 1990 and 2018 is 0.87. This suggests that there is a long-term trend of increasing CO2e emissions per capita.

In [ ]:
numeric_data['Continent']=Copy_data_set['Continent']

In [ ]:
grouped_continent=numeric_data.groupby('Continent').mean()
grouped_continent=grouped_continent.transpose().reset_index()
grouped_continent.rename(columns={'index':'years '})

In [ ]:
melted_df=grouped_continent.melt(id_vars=['index'],value_vars=grouped_continent[1:], var_name="Continent", 
                                       value_name="Emissions")

In [ ]:
plt.figure(figsize=(10,6))
fig=px.line(melted_df,x='index',y='Emissions',color='Continent',title="Mean Emissions by Continent Over the Years",
              labels={"Emissions": "Metric tons of CO2e per capita"})
fig.show()

In [ ]:

Percentage_change=pd.DataFrame()
Africa=(grouped_continent['Africa'][6]-grouped_continent['Africa'][0])/grouped_continent['Africa'][0]*100
Asia=(grouped_continent['Asia'][6]-grouped_continent['Asia'][0])/grouped_continent['Asia'][0]*100
America =(grouped_continent['America'][6]-grouped_continent['America'][0])/grouped_continent['America'][0]*100
Europe =(grouped_continent['Europe'][6]-grouped_continent['Europe'][0])/grouped_continent['Europe'][0]*100
Oceania=(grouped_continent['Oceania'][6]-grouped_continent['Oceania'][0])/grouped_continent['Oceania'][0]*100

In [ ]:
Percentage_change['Continent']=['Africa','Asia','Europe','America','Oceania']

Percentage_change['Co2 Percentage change']=[Africa,Asia,Europe,America,Oceania]
Percentage_change

In [ ]:
px.bar(Percentage_change,x='Continent',y='Co2 Percentage change',title='Co2 emissions  percentage change since 1990 ',color='Co2 Percentage change')

 In a global sprint fueled by carbon, Europe breaks from the pack, running in reverse. Asia and Africa sprint ahead, pushing the climate crisis ever closer, while Europe offers a tantalizing glimpse of a finish line where air is clear and skies are blue.

In [ ]:
grouped_hemisphere=Copy_data_set.groupby('Hemisphere').mean()
grouped_hemisphere=grouped_hemisphere.transpose()

In [ ]:
grouped_hemisphere.reset_index(inplace=True)

In [ ]:
grouped_hemisphere['Years']=[1990,1995,2000,2005,2010,2013,2019]

In [ ]:
grouped_hemisphere

In [ ]:
melted_df_hemisphere=grouped_hemisphere.melt(id_vars='Years',value_vars=['Northern Hemisphere','Southern Hemisphere'])

In [ ]:
melted_df_hemisphere

In [ ]:
px.line(melted_df_hemisphere,x='Years',y='value',color='Hemisphere')

In [ ]:
Copy_data_set.sort_values(by=['Metric tons of CO2e per capita (2018)'],ascending=False,inplace=True)
Copy_data_set

In [ ]:
Most_poluted_countries=pd.DataFrame(columns=['Country','Metric tons of CO2e per capita (2018)','Hemisphere'])

In [ ]:
Copy_data_set.sort_values(by='Metric tons of CO2e per capita (2018)',ascending=False,inplace=True)
Most_poluted_countries['Country']=Copy_data_set['Country'].head(15)
Most_poluted_countries['Metric tons of CO2e per capita (2018)']=Copy_data_set['Metric tons of CO2e per capita (2018)'].head(15)
Most_poluted_countries['Hemisphere']=Copy_data_set['Hemisphere'].head(15)

In [ ]:
Most_poluted_countries

In [ ]:
px.bar(Most_poluted_countries,x='Country',y='Metric tons of CO2e per capita (2018)',color='Metric tons of CO2e per capita (2018)',title='Most polluted counties')

In [ ]:
Copy_data_set

In [ ]:
Copy_data_set['Pecentage_change_countries']=(Copy_data_set['Metric tons of CO2e per capita (2018)']-Copy_data_set['Metric tons of CO2e per capita (1990)'])/Copy_data_set['Metric tons of CO2e per capita (1990)']*100

In [ ]:
Copy_data_set.sort_values(by='Pecentage_change_countries',ascending=False,inplace=True)

In [ ]:
px.bar(data_frame=Copy_data_set,x=Copy_data_set['Country'].head(10),y=Copy_data_set['Pecentage_change_countries'].head(10),color=Copy_data_set['Continent'].head(10),title='Countries with highest change in CO2 emssions since 1990 ')

In [ ]:
px.bar(data_frame=Copy_data_set,x=Copy_data_set['Country'].tail(10),y=Copy_data_set['Pecentage_change_countries'].tail(10),color=Copy_data_set['Continent'].tail(10),
title='Countries with lowest change in CO2 emssions since 1990 ')

In [ ]:
Copy_data_set

In [ ]:
Main_data_set

# 5. **Conclusion**

Conclusion
From the analysis, it can be concluded that
* Asia has the highest carbon footprint, followed by Africa.
* Europe is the only continent with a negative net annual CO2 emissions release.
* The Northern Hemisphere exhibits substantially higher CO2 emissions compared to the Southern Hemisphere, likely due to its composition of four major continents.
* Although Asia currently leads in carbon footprint, Africa is making strides to catch up.